#!/bin/bash -e

# Map environment variables to entries in logstash.yml.
# Note that this will mutate logstash.yml in place if any such settings are found.
# This may be undesirable, especially if logstash.yml is bind-mounted from the
# host system.
env2yaml /usr/share/logstash/config/logstash.yml

export LS_JAVA_OPTS="-Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/ $LS_JAVA_OPTS"

./envsubst < consul-register.json > consul.json

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
  exec logstash "$@" > logstash.log &
else
  exec "$@" > logstash.log &
fi

until [ $(curl -s -o out.html -w '%{http_code}'  http://localhost:9600;) -eq 200 ]; do
   sleep 1
done

curl -X PUT -d @consul.json http://$CONSUL:8500/v1/agent/service/register -v
tail -f logstash.log
